FLASK_SERVER_NAME = 'localhost:1337'
FLASK_DEBUG = True #CHANGE BEFORE DEPLOYMENT
FLASK_THREADED = True

RESTPLUS_SWAGGER_EXPANSION = 'list'
RESTPLUS_VAL = True
RESTPLUS_MASK_SWAGGER = False

SQLALCHEMY_DATABASE_URI = 'mysql://root:@127.0.0.1:3306/stock_analysis'
SQLALCHEMY_TRACK_MODIFICATIONS = False

JSON_SORT_KEYS = False