name: Postman API Tests

on:
  push:
    branches: 
      - main
      - develop
      - julien-action-patch
  pull_request:
    branches: 
      - main 
      - develop

jobs:
  Postman-Tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Start mySQL
      run: sudo service mysql start
    - name: Configure mySQL     
      run:  mysqladmin -u root -proot password ''
    - name: Import database
      run: |
        echo $DB_DUMP_FILE > db.sql
        #mysql -u root < db.sql
        mysql -u root -e 'source db.sql'
      env:
        DB_DUMP_FILE : ${{secrets.SQL_DB}}
    - name: Test dump
      run: cat db.sql
    - name: Show Database names
      run: mysql -u root -e 'SHOW DATABASES;'
    - name: Test Database with brilliant name 'Database'
      run: mysql -u root -D Database -e 'SHOW TABLES;'
    - name: Test Database 'mysql'   
      run: mysql -u root -D mysql -e 'SHOW TABLES;'

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Start Backend
      run: |
        cd StockAnalysisAPI
        python app.py profile:develop &
    
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install Newman
      run: npm install -g newman
    
    - name: Run Postman Tests
      run: newman run StockAnalysisAPI/StockAnalysisAPI.postman_collection.json
